### ISSUE TITLE
קביעת יח לימוד בתפריט הצף

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-app#117]
אחרי שאני קובע יח לימוד מסוימת, לדוגמה פסקאות, דרך התפריט הצף, ואני עובר למסך ההגדרות כדי לשנות את זה, וחוזר לשיעור, זה לא משתנה אלא נשאר בפסקאות

**Comment by walteryaron** [comment]
לא יודע למה זה פתוח
