### ISSUE TITLE
תפריט צף לא פועל

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-app#118]
ייתכן שזה כאשר אין לא ניקוד ולא טעמים
אתה יכול לראות בקליפ ספירה לבדיקה שמשויך אליך
j1baec0PoB
![image](https://cloud.githubusercontent.com/assets/6491631/5887935/0b1edd58-a3f3-11e4-9da8-da9172eb713e.png)

**Comment by walteryaron** [comment]
טופל בהצגה
אולי צריך לשנות משהו אבל כרגע עובד

**Comment by natan1957** [comment]
עדיין לא תקין

**Comment by natan1957** [comment]
התפריט הצף מכיל את יחידות הלימוד, לא מכיל את האפשרות לשנות את גודל הפונט ובמקום שורת הניקוד מופיע פס שחור מיותר.
![image](https://cloud.githubusercontent.com/assets/6491631/6542078/606dc6a6-c4f6-11e4-945a-edc313dcb0d8.png)

**Comment by walteryaron** [comment]
הוספתי את מה שהיה חסר
פלוס לחיצה מסביב סוגרת את התפריט

**Comment by natan1957** [comment]
![image](https://cloud.githubusercontent.com/assets/6491631/6545382/57a1de80-c58d-11e4-8e7b-62fdf03466b4.png)

**Comment by walteryaron** [comment]
אני לא הולך לתקן את הניראות
אתה רצית שתי שורות
אין לי איך לבטל אותם
צריך מחיים תפריט אחר וחיים כבר לא עובד איתנו

**Comment by natan1957** [comment]
שלח לי את הקובץ הגרפי של התפריט הקיים.
יש גרסה של 4+4 ויש 4+2. שלח לי את שתיהן.

**Comment by natan1957** [comment]
מה עם הקבצים הגרפיים?
