### ISSUE TITLE
לא ניתן להפעיל בנגיעה כאשר מתג קטעים סגור.

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-app#119]
לאחר שאני מעביר בהגדרות שיעור את מתג קטעים ל אוף
אני חוזר לשיעור, המסך לא רגיש לנגיעות ולא ניתו להפעיל את השיעור בלחיצה על הטקסט.

**Comment by walteryaron** [comment]
טופל

**Comment by natan1957** [comment]
כאשר חוזרים ממצב קטעים נעולים ללא נעולים המערכת ממשיכה להתנהג כאילו הם נעולים

**Comment by walteryaron** [comment]
לא מצליח לשחזר את זה בגירסה האחרונה

**Comment by natan1957** [comment]
יש להפעיל שיעור כשכל המתגים פעילים.
יש להקליק על קטעים ולראות שעובד תקין.
יש לעבור להגדרות ולבגור את קטעים ומשפטים.
יש לחזור לשיעור ולהקליק ולראות שמפעיל פסקאות.
יש לחזור להגדרות ולהפעיל את קטעים ומשפטים
יש לחזור לשיעור ולהקליק ולבדוק אם קטעים מופעל.
אצלי בשלב הזה הוא ממשיך להפעיל פסקאות למרות שמתג קטעים מופעל.

**Comment by natan1957** [comment]
שלחתי קליפ

**Comment by natan1957** [comment]
מה עם זה...

**Comment by natan1957** [comment]
אחרי סגירת מתגים קטעים משפטים ופסקאות ואחרי פתיחתם לא ניתן לנגן ע"י נגיעה במסך אלא מנגן רק את כל השיעור
