### ISSUE TITLE
השהיה מיותרת

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-app#120]
בסיום הקלטה משותפת למורה ותלמיד ולפני ההשמעה שלה, ישנה השהיה שלא הייתה קודם ולא צריכה להיות.
ניתן להבחין בזה כשהקטע ארוך, פסוק של או פסקה.
ההשהיה היא ביחס ישר לגודל יחידת הלימוד. זה מזכיר לי את זמן העצירה האוטומטית ההקלטה ב"עכשיו אתה" כאשר לא לוחצים על עצירה.

**Comment by walteryaron** [comment]
טופל

**Comment by natan1957** [comment]
בסיום הקלטה משותפת ולפני השמעתה עדיין יש בלגן בהנחיה הקולית

**Comment by walteryaron** [comment]
טופל

**Comment by natan1957** [comment]
ההנחיה הקולית "הקשב לשנינו" עדיין לא מושמעת.

**Comment by natan1957** [comment]
שלחתי קליפ

**Comment by walteryaron** [comment]
טופל

**Comment by natan1957** [comment]
כלום לא השתנה בגרסה 6 איפון 4

**Comment by walteryaron** [comment]
יש בעיה בגירסה 6
פעם זה עובד פעם זה לא עובד
תבדוק תראה שאני צודק
אין לי אפשרות לפתור את זה
bug של אפל ידוע

**Comment by natan1957** [comment]
לא מבין איזה באג... באפליקציה
My Mentorah
זה עובד טוב ויציב. 
גם ב MyMentorApp
זה עבד עד שרק לאחרונה השתבש..
אני לא רואה שפעם עובד ופעם לא. תמיד לא עובד בגרסה 6. 
עכשיו, אין לי מושג מה קורה ב 7...
ענייני התזמון הם החלק הכי חשוב באפליקציה. אי אפשר להשאיר את זה למזל....


נשלח מה-iPhone שלי

ב-Mar 18, 2015, בשעה 17:38, yaron walter <notifications@github.com> כתב/ה:

> 
> יש בעיה בגירסה 6
> פעם זה עובד פעם זה לא עובד
> תבדוק תראה שאני צודק
> אין לי אפשרות לפתור את זה
> bug של אפל ידוע
>

**Comment by natan1957** [comment]
מה עם זה ?
