### ISSUE TITLE
זרימה לא תקינה של רישום

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-app#123]
כאשר משתמש עובר למסך רישום, הוא ממלא פרטים ולוחץ רישום, מופיע טופס חדש, ריק, שמחייב אותו למלא את הפרטים שוב.
![image](https://cloud.githubusercontent.com/assets/6491631/6332735/621c63d2-bb90-11e4-8ae4-0ac9bc43cf58.png)

**Comment by walteryaron** [comment]
אתה מתבלבל
ישנם שני מסכים
אחד רישום השני לוגין
כאשר אתה בלוגין אתה צריך ללחוץ לוגים או go במקלדת
אתה לא יכול לרשום את הפרטים ואז ללחוץ register
זה יפנה אותך למסך חדש של register

**Comment by natan1957** [comment]
טופס הרישום צריך לכלול שלושה שדות, יש להקליד את הסיסמה פעמיים
אם המשתמש מקליד פרטים בטופס הכניסה ומקיש רישום, השם והסיסמה צריכים לעבור לטופס הרישום ושם הוא צריך להשלים את הסיסמה השניה.

אם הוא לא ממלא פרטים אלא ישר מקיש רישום, הוא יקבל טופס ריק עם שלושת השדות להקלדה.

תכל'ס, לא ברור לי מה שינית בגרסה 5

**Comment by walteryaron** [comment]
לא דיברנו על זה
השינוי היה שאם הייתה נרשם ויוצא מהאפליקציה
בכניסה מחדש הייתה לא רשום
בכל המסכים זה היה קורה
זה התיקון
זה שינוי שאף פעם לא דיברנו עליו
למה שיעברו הפרטים לרישום
כל אפליקציה היום שאתה פותח לא עושה את זה
או שיש רישום או שיש כניסה
אל תמציא את הגלגל

**Comment by natan1957** [comment]
ירון, אני לא ממציא את הגלגל.
בכל טופס לוג אין יש אפשרות גישה לטופס רישום. 
אבל הגישה היא לא עם כפתור שנמצא ליד הלוגאין ובגודל שלו אלא בדרך כלל לינק בתחתית המסך.

במקרה שלנו הכפתורים נמצאים זה לצד זה והמשתמש עלול לחשוב שאם ימלא את פרטים וילחץ על רישום, יתבצע רישום.
למקרה שזה יקרה, ביקשתי שבמעבר לטופס רישום, נתונים מטופס הכניסה יועתקו לטופס הרישום כדי שלא יצטרך לרשום אותם שוב.
בנוסף, מכיון שהוא לא רואה את הסיסמה, יש להקליד אותה פעם נוספת ולבדוק התאמה.
מה כל כך קשה בזה ?

ראה מסכי לוגאין של אפליקציות
![image](https://cloud.githubusercontent.com/assets/6491631/6429931/2d4627fa-bffb-11e4-99ba-d04f9d983de4.png)

![image](https://cloud.githubusercontent.com/assets/6491631/6429934/454e224e-bffb-11e4-9ff0-d133c3012d9c.png)

![image](https://cloud.githubusercontent.com/assets/6491631/6429936/63ef3a44-bffb-11e4-947a-b21de7261a57.png)

![image](https://cloud.githubusercontent.com/assets/6491631/6429939/870fef46-bffb-11e4-939f-aabd11727d89.png)

![image](https://cloud.githubusercontent.com/assets/6491631/6429944/a80011f4-bffb-11e4-8d35-bf196594f49e.png)

![image](https://cloud.githubusercontent.com/assets/6491631/6429950/d7dca5b8-bffb-11e4-9ba0-e70d0ede65da.png)

**Comment by walteryaron** [comment]
תחילף את המלל ל
new user signup או משהו בסגנון
כל השאר עובד בדיו׳ כמו במסכים שהעלת

**Comment by natan1957** [comment]
הכניסה לרישום בממשק העברי מתעופפת
שלחתי קליפ

**Comment by walteryaron** [comment]
בדקתי על iOS 6  אצלי
ואין בעיה

**Comment by natan1957** [comment]
בממשק אנגלי זה עובד. 
בממשק עברי זה עף.

**Comment by walteryaron** [comment]
שוב
אצלי זה עובד

**Comment by natan1957** [comment]
עכשיו זה עובד.. מדאיג אותי שלמעשה לא ברור מה היה, בגרסה 7 זה עף בוודאות בכל ניסיון רישום בממשק עברי בלבד
אני סוגר את התקלה, מקווה שלא תחזור.

**Comment by walteryaron** [comment]
טעות שלי
בדקתי תמיד על אנגלית בכל המכשירים ולא ראיתי שרשום עברית
