### ISSUE TITLE
אי התאמה בין תפריט צף למתגים

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-app#124]
בממשק האנגלי, אם אני מפעיל את התפריט הצף ובוחר קטעים ואחר כך עובר לאפשרויות, אני רואה שרק כל השיעור פתוח.
וההפך.
![image](https://cloud.githubusercontent.com/assets/6491631/6429980/28bd446e-bffd-11e4-9840-17aec8442339.png)
![image](https://cloud.githubusercontent.com/assets/6491631/6429984/430affd2-bffd-11e4-93c5-ab1bfcda94a4.png)

**Comment by walteryaron** [comment]
טופל
הייתה בעיה עם השפה

**Comment by walteryaron** [comment]
הוספתי בדיקה
זה תקין לפי מה ששלחת
