### ISSUE TITLE
השמעת הקלטה משותפת

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-app#126]
כאשר מפעילים ללא אזניות, ההשמעה כוללת את ההקלטה מהמיקרופון בלבד.
אבל אם באמצע ההשמעה מקישים על פאוז, במקום לעצור, זה משמיע את הסאונד של השיעור.
שולח קליפ.

**Comment by walteryaron** [comment]
טופל

**Comment by natan1957** [comment]
עכשיו בפאוז זה עוצר אבל בפליי זה משמיע שוב את הסאונד של השיעור בתוספת הסאונד שהוקלט בשלב ההקלטה המשותפת

**Comment by natan1957** [comment]
מה עם זה...
