### ISSUE TITLE
זמן הקלטה עכשיו אתה

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-app#128]
נתקלתי במצב פעמיים בו לא ניתן זמן להקלטה.
ההקלטה התחילה ומיד נסגרה.

בנוסף העניין של הורדת ההקלטה ל 100% ולא 110 זה ממש לא טוב.

**Comment by natan1957** [comment]
שלחתי קליפ

**Comment by walteryaron** [comment]
Fixed
