### ISSUE TITLE
התעופפות סטטוס שיעור בסך

### ISSUE THREAD

**Issue by natan1957** [natan1957/mymentor-app#130]
user talmid66@gmail.com   
pw talmid66
Purchases key ZORRnVQYJf
clip e96gM6sFUw
מעיף את האפליקציה למרות שהסטטוס שלו 
Lesson_Is_In_Basket
האפליקציה אמורה להתעלם מהסטטוס הזה.
בכל מקרה נראה לי שגם הקליפ בעייתי כי כשאני משנה לסטטוס שיעור פעיל זה גם עף.

**Comment by natan1957** [comment]
מצאתי שזה קורה כאשר בשדות
description_he_il/en_us
remarks_he_il/en_us
יש ערך
(null)
יש לאפשר ערך כזה בלי לעוף

**Comment by walteryaron** [comment]
Fixed
